/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-tertiary": "#ffffff",
          "on-surface": "#1b1c1c",
          "surface-container-low": "#f6f3f2",
          "on-primary-fixed": "#001a41",
          "primary-fixed": "#d8e2ff",
          "surface": "#fcf9f8",
          "outline-variant": "#c4c6d0",
          "surface-variant": "#e5e2e1",
          "surface-dim": "#dcd9d9",
          "on-error-container": "#93000a",
          "outline": "#747780",
          "on-tertiary-fixed-variant": "#41474e",
          "surface-tint": "#475e8c",
          "on-surface-variant": "#44474f",
          "inverse-primary": "#afc6fb",
          "on-primary-container": "#8ba2d5",
          "error": "#ba1a1a",
          "tertiary-container": "#33393f",
          "inverse-on-surface": "#f3f0ef",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed-dim": "#adc6ff",
          "on-tertiary-container": "#9ca3aa",
          "background": "#fcf9f8",
          "tertiary": "#1d2429",
          "on-primary": "#ffffff",
          "primary": "#03224d",
          "primary-fixed-dim": "#afc6fb",
          "surface-bright": "#fcf9f8",
          "on-secondary": "#ffffff",
          "primary-container": "#1f3864",
          "surface-container-high": "#eae7e7",
          "tertiary-fixed": "#dde3eb",
          "tertiary-fixed-dim": "#c1c7cf",
          "surface-container": "#f0eded",
          "on-secondary-container": "#1e4587",
          "on-secondary-fixed": "#001a42",
          "secondary-fixed": "#d8e2ff",
          "on-background": "#1b1c1c",
          "on-tertiary-fixed": "#161c22",
          "surface-container-highest": "#e5e2e1",
          "secondary": "#395da0",
          "on-secondary-fixed-variant": "#1d4586",
          "secondary-container": "#93b6fe",
          "error-container": "#ffdad6",
          "on-primary-fixed-variant": "#2e4673",
          "on-error": "#ffffff",
          "inverse-surface": "#303030"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-md": "16px",
          "margin-desktop": "48px",
          "stack-sm": "8px",
          "container-max": "1280px",
          "gutter": "24px",
          "stack-xl": "64px",
          "margin-mobile": "16px",
          "stack-lg": "32px"
      },
      "fontFamily": {
          "headline-lg": ["Inter"],
          "label-md": ["Inter"],
          "display-lg": ["Inter"],
          "headline-md": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"],
          "label-sm": ["Inter"]
      },
      "fontSize": {
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
          "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
